# Generated by Django 4.1.2 on 2022-11-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogga_users", "0002_bloggauser_is_staff_alter_bloggauser_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloggauser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="bloggauser",
            name="occupation",
        ),
    ]
